"""empty message

Revision ID: 125e72b88866
Revises: 8c92212e73e8
Create Date: 2020-05-06 18:13:58.413602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125e72b88866'
down_revision = '8c92212e73e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follows', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('follows_user_id_fkey', 'follows', type_='foreignkey')
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_user_id_fkey', 'likes', type_='foreignkey')
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('likes_user_id_fkey', 'likes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'posts', ['post_id'], ['id'])
    op.alter_column('likes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('follows_user_id_fkey', 'follows', 'users', ['user_id'], ['id'])
    op.alter_column('follows', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
